version: '3.7'

services:
  api:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - '/api'
    ports:
      - 5002:5000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@mock-db:5432/shops
  
    depends_on: 
        - mock-db

  mock-db:
    build:
      context: ./back-end/database
      dockerfile: Dockerfile
    ports: 
        - 5436:5432
    environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      
    
  nginx:
    image: linuxserver/letsencrypt
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/config/nginx/nginx.conf
      - ./dev.conf:/config/nginx/site-confs/default
    environment:
      - PUID=1050
      - PGID=1050
      - EMAIL=ulyses.sosa@gmail.com
      - URL=ulises-codes.me
      - ONLY_SUBDOMAINS=true
      - STAGING=true 
      - TZ=Italy/Rome
    depends_on:
      - api
      - client
      
  client:
    build:
        context: ./front-end
        dockerfile: Dockerfile
    volumes:
      - '/client'

    ports:
      - 3000:3000
    
    depends_on:
      - api
