version: "3.7"

services:
  api:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - "/api"
    ports:
      - 5002:5000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@mock-db:5432/shops
      - FLASK_CONFIG=development
      - FLASK_ENV=development
      - APP_SETTINGS=config.DevelopmentConfig
      - SECRET_KEY=ZQbn05PDeA7v11
    depends_on:
      - mock-db

  mock-db:
    build:
      context: ./back-end/database
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - api
      - client

  client:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - "/client"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000

    depends_on:
      - api
