import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
import { Scrollbars } from "react-custom-scrollbars";
import kPoints from "./../Data/points.json";
import showFunc from '../Data/kmeans-clusters'
import Layout,{siteTitle} from "../component/Layout/Layout";
import Shop from '../component/Shop'
import { Button, ButtonGroup } from "@material-ui/core";
import dBPoints from '../Data/dbscan-clusters';



export async function getStaticProps(){
  const originalPoints = kPoints;
  const kOrganizedPoints = showFunc(originalPoints);
  const dbOrganizedPoints = dBPoints(originalPoints);

  return {
    props : {originalPoints,kOrganizedPoints, dbOrganizedPoints}
  }
}


export default function Home({originalPoints, kOrganizedPoints,dbOrganizedPoints}) {
  const MapWithNoSSR = dynamic(() => import("../component/Map/map"), {
    ssr: false,
  });

  const [markers, setMarkers] = useState(originalPoints);
  
  const[shop,setShop]= useState(null);

  // const calculateKMeansHandler= () => {
  //   setMarkers(()=> showFunc(markers).markers )
  // }

  const findInMap = (shop) => {
    setShop((current) => current = shop);
  }


  return (

  
    <Layout home>

        <Head>
          <title>{siteTitle}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <section>

          <h1 className={styles.title}>Starbucks in the world</h1>
          <h2 className={styles.description}>- Application of DBScan and K-Means algorithms -</h2>
        </section>

        
        <section className={styles.cardsContainer}>
          
          <div className={styles.infoblock}>
            <div className={styles.map}>
              <MapWithNoSSR  markers= {markers} shop={shop}/>   
            </div>
          
            <div className={styles.sidebar}>
            <div className={styles.buttonset}>

            <ButtonGroup variant="text" size="large" color="primary" aria-label="text primary button group">
              <Button onClick={()=> setMarkers(kOrganizedPoints.markers)}>Means Clustering</Button>
              <Button onClick={()=> setMarkers(dbOrganizedPoints.markers)}>DBScan</Button>
              <Button onClick={()=> {setMarkers(originalPoints);setShop(null)}}>Reset</Button>
            </ButtonGroup>


              </div>
              <Scrollbars>
                {markers.map((point,index)=> {
              //    console.log("Point",point)
                return <Shop
                  key={[point.Lat, point.Lon,point.Address],index}
                  clicked={() => findInMap(point)}
                  city={point.City}
                  address={point.Address}
                  sqmt={point.Sqmt}
                  color={point.Color}
                  />
                  })}
              </Scrollbars>
            </div>
          </div>
        </section>
          
    </Layout>
  );
}
