import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
import { Scrollbars } from "react-custom-scrollbars";
import Points from "./../Data/points.json";
import showFunc from './../Data/DataAnalysis'
import Layout,{siteTitle} from "../component/Layout/Layout";
import Shop from '../component/Cards'
import { Button, ButtonGroup } from "@material-ui/core";



export async function getStaticProps(){
  const organizedPoints = showFunc(Points);
  const originalPoints = Points;
  return {
    props : {originalPoints,organizedPoints}
  }
}



export default function Home({originalPoints, organizedPoints}) {
  const MapWithNoSSR = dynamic(() => import("../component/Map/map"), {
    ssr: false,
  });

 const [markers, setMarkers] = useState(originalPoints);

    
  
  
  const[shop,setShop]= useState(null);

  const findInMap = (shop) => {
    setShop((current) => current = shop);
  }

  return (

    
    <Layout home>

        <Head>
          <title>{siteTitle}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <section>

          <h1 className={styles.title}>Starbucks in the world</h1>
          <h2 className={styles.description}>- Colored marked by size -</h2>
        </section>

        
        <section className={styles.cardsContainer}>
          
         

         
          <div className={styles.infoblock}>
            <div className={styles.map}>
              <MapWithNoSSR  markers= {markers} shop={shop}/>   
            </div>
          
            <div className={styles.sidebar}>
            <div className={styles.buttonset}>

            <ButtonGroup variant="text" size="large" color="primary" aria-label="text primary button group">
              <Button onClick={()=>setMarkers(organizedPoints.markers)}>Means Clustering</Button>
              <Button>DBScan</Button>
              <Button onClick={()=> setMarkers(originalPoints)}>Reset</Button>
            </ButtonGroup>


              </div>
              <Scrollbars>
                {originalPoints.map((point)=> {
                //  console.log("Point",point)
                return <Shop
                  key={[point.Lat, point.Lon,point.Address]}
                  clicked={() => findInMap(point)}
                  city={point.City}
                  address={point.Address}
                  sqmt={point.Sqmt}
                  />})}
              </Scrollbars>
            </div>
          </div>
        </section>
          
    </Layout>
  );
}
